### ISSUE TITLE
[BUG] Update video different sizes

### ISSUE THREAD

**Issue by darigovresearch** [ONEARMY/project-kamp-academy#12]
Is there a reason why the previous videos in the update page different sizes than the latest video?

Page in question - https://community.projectkamp.com/academy/updates/video

![image](https://user-images.githubusercontent.com/30328618/123510105-83740780-d671-11eb-9117-d8d00ac5afbe.png)

**Comment by davehakkens** [comment]
nope. No reason. I think just different embed code?
And thanks for adding them!

**Comment by darigovresearch** [comment]
Thanks for the guidance @davehakkens ! Pull request #19 should resolve this if merged
