### ISSUE TITLE
[QUESTION] Delete old buy land.md file

### ISSUE THREAD

**Issue by darigovresearch** [ONEARMY/project-kamp-academy#13]
Is there a reason why the old buy land is still in the repository?

May be good to delete/deprecate it if it is not needed

File in question - https://github.com/ONEARMY/project-kamp-academy/blob/master/docs/land/buy_old.md

**Comment by davehakkens** [comment]
Nope. Just some legacy trash. Can be removed

**Comment by darigovresearch** [comment]
Thanks. pull request #27 would resolve this issue if merged
