### ISSUE TITLE
[FEATURE REQUEST] Add edit button to pages

### ISSUE THREAD

**Issue by darigovresearch** [ONEARMY/project-kamp-academy#17]
Precious plastic has an edit button at the bottom of the page, it encourages people to contribute in a very easy way

![image](https://user-images.githubusercontent.com/30328618/123541314-c13d6280-d73b-11eb-9b49-ed5894a4828c.png)

**Comment by davehakkens** [comment]
Yeh would be good!
I think this a setting in the config file..

**Comment by darigovresearch** [comment]
Pull request #18 which has been merged resolves this issue
