### ISSUE TITLE
Put Project Kamp academy under onearmy

### ISSUE THREAD

**Issue by darigovresearch** [ONEARMY/project-kamp-academy#3]
Wanted to make copywrite improvements & had to find it here but only knew to find it here due to experience in the ecosystem.

If other people want to make fixes/improvements it would be more discoverable under the onearmy organisation

**Comment by davehakkens** [comment]
Done. Should be there in a few minutes

**Comment by darigovresearch** [comment]
Thanks, can confirm that this has now been ported to the ONEARMY account and that this issue can be closed
