### ISSUE TITLE
Expanding comments locks scrolling on Chrome

### ISSUE THREAD

**Issue by knoopx** [ONEARMY/project-kamp-academy#32]
* Visit https://community.projectkamp.com/research/can-we-setup-a-screw-system-for-a-community
* Click "View N Comments"
* Scroll up/down

I'll take a look later and see if I can fix it myself

**Comment by knoopx** [comment]
Uhmm wrong repo, figuring out where the real thing is...

**Comment by davehakkens** [comment]
haha thanks for making an issue. here is the correct one https://github.com/ONEARMY/community-platform
